# Problem Statement and Data Description

**Customer Churn Prediction:** 

A Bank wants to take care of customer retention for its product: savings accounts. The bank wants you to identify customers likely to churn balances below the minimum balance. You have the customers information such as age, gender, demographics along with their transactions with the bank.
Your task as a data scientist would be to predict the propensity to churn for each customer.

**Data Dictionary**

There are multiple variables in the dataset which can be cleanly divided into 3 categories:

I. Demographic information about customers
•	customer_id - Customer id 
•	vintage - Vintage of the customer with the bank in a number of days 
•	age - Age of customer 
•	gender - Gender of customer 
•	dependents - Number of dependents 
•	occupation - Occupation of the customer 
•	city - City of the customer (anonymized) 
II. Customer Bank Relationship
•	customer_nw_category - Net worth of customer (3: Low 2: Medium 1: High) 
•	branch_code - Branch Code for a customer account 
•	days_since_last_transaction - No of Days Since Last Credit in Last 1 year 
III. Transactional Information
•	current_balance - Balance as of today 
•	previous_month_end_balance - End of Month Balance of previous month 
•	average_monthly_balance_prevQ - Average monthly balances (AMB) in Previous Quarter 
•	average_monthly_balance_prevQ2 - Average monthly balances (AMB) in previous to the previous quarter 
•	current_month_credit - Total Credit Amount current month 
•	previous_month_credit - Total Credit Amount previous month 
•	current_month_debit - Total Debit Amount current month 
•	previous_month_debit - Total Debit Amount previous month 
•	current_month_balance - Average Balance of current month 
•	previous_month_balance - Average Balance of previous month 
•	churn - Average balance of customer falls below minimum balance in the next quarter (1/0)

# Loading the Dataset

In [24]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [25]:
df = pd.read_csv(r'C:\Users\Manish Gupta\Desktop\ML Training\Final Project\Final project problem statement and dataset\churn_prediction.csv')
df.shape

(28382, 21)

In [5]:
df.head()         #Data Exploration Begins

,customer_id,vintage,age,gender,dependents,occupation,city,customer_nw_category,branch_code,days_since_last_transaction,...,previous_month_end_balance,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,previous_month_credit,current_month_debit,previous_month_debit,current_month_balance,previous_month_balance,churn
0,1,3135,66,Male,0.0,self_employed,187.0,2,755,224.0,...,1458.71,1458.71,1449.07,0.20,0.20,0.20,0.20,1458.71,1458.71,0
1,2,310,35,Male,0.0,self_employed,NaN,2,3214,60.0,...,8704.66,7799.26,12419.41,0.56,0.56,5486.27,100.56,6496.78,8787.61,0
2,4,2356,31,Male,0.0,salaried,146.0,2,41,NaN,...,5815.29,4910.17,2815.94,0.61,0.61,6046.73,259.23,5006.28,5070.14,0
3,5,478,90,NaN,NaN,self_employed,1020.0,2,582,147.0,...,2291.91,2084.54,1006.54,0.47,0.47,0.47,2143.33,2291.91,1669.79,1
4,6,2531,42,Male,2.0,self_employed,1494.0,3,388,58.0,...,1401.72,1643.31,1871.12,0.33,714.61,588.62,1538.06,1157.15,1677.16,1

In [6]:
df.columns

Index(['customer_id', 'vintage', 'age', 'gender', 'dependents', 'occupation',
       'city', 'customer_nw_category', 'branch_code',
       'days_since_last_transaction', 'current_balance',
       'previous_month_end_balance', 'average_monthly_balance_prevQ',
       'average_monthly_balance_prevQ2', 'current_month_credit',
       'previous_month_credit', 'current_month_debit', 'previous_month_debit',
       'current_month_balance', 'previous_month_balance', 'churn'],
      dtype='object')

# Imputing Missing Values

In [7]:
df.isnull().sum()            #Checking Missing Values

customer_id                          0
vintage                              0
age                                  0
gender                             525
dependents                        2463
occupation                          80
city                               803
customer_nw_category                 0
branch_code                          0
days_since_last_transaction       3223
current_balance                      0
previous_month_end_balance           0
average_monthly_balance_prevQ        0
average_monthly_balance_prevQ2       0
current_month_credit                 0
previous_month_credit                0
current_month_debit                  0
previous_month_debit                 0
current_month_balance                0
previous_month_balance               0
churn                                0
dtype: int64

In [8]:
df[['gender','dependents','occupation','city','days_since_last_transaction']].head()

  gender  dependents     occupation    city  days_since_last_transaction
0   Male         0.0  self_employed   187.0                        224.0
1   Male         0.0  self_employed     NaN                         60.0
2   Male         0.0       salaried   146.0                          NaN
3    NaN         NaN  self_employed  1020.0                        147.0
4   Male         2.0  self_employed  1494.0                         58.0

**1. Missing Values in Gender**

In [10]:
df['gender'].value_counts()                 #Imputing with Mode of Gender as Cateorical Var

Male      16548
Female    11309
Name: gender, dtype: int64

In [11]:
df['gender'].fillna('Male', inplace=True)

**2. Missing Values in Dependents**

In [12]:
df['dependents'].value_counts()       #Since Categorical Variable, Imputing with Mode

0.0     21435
2.0      2150
1.0      1395
3.0       701
4.0       179
5.0        41
6.0         8
7.0         3
36.0        1
52.0        1
25.0        1
9.0         1
50.0        1
32.0        1
8.0         1
Name: dependents, dtype: int64

In [13]:
df['dependents'].fillna('0.0', inplace=True)

**3. Missing Values in Occupation **

In [14]:
df['occupation'].value_counts()

self_employed    17476
salaried          6704
student           2058
retired           2024
company             40
Name: occupation, dtype: int64

In [15]:
df['occupation'].fillna('self_employed', inplace=True)

**4. Missing Values in City **

In [16]:
df['city'].value_counts()

1020.0    3479
1096.0    2016
409.0     1334
146.0     1291
834.0     1138
334.0      930
1232.0     840
623.0      778
15.0       669
575.0      631
1525.0     375
905.0      345
491.0      312
1111.0     312
1494.0     289
649.0      281
1589.0     251
318.0      245
1084.0     240
61.0       237
531.0      227
656.0      197
904.0      187
630.0      166
1181.0     150
1271.0     150
1076.0     133
745.0      130
996.0      119
621.0      114
          ...
1179.0       1
1421.0       1
973.0        1
847.0        1
1001.0       1
1279.0       1
1137.0       1
1245.0       1
1594.0       1
948.0        1
1026.0       1
1166.0       1
1545.0       1
808.0        1
503.0        1
1300.0       1
1605.0       1
824.0        1
607.0        1
1011.0       1
728.0        1
1207.0       1
566.0        1
972.0        1
1448.0       1
629.0        1
527.0        1
1212.0       1
530.0        1
70.0         1
Name: city, dtype: int64

In [17]:
df['city'].fillna('1020.0', inplace=True)

**5. Missing Values in Days Since Last Transaction **

In [18]:
df['days_since_last_transaction'].value_counts()

0.0      1672
3.0       831
14.0      654
4.0       632
6.0       596
5.0       576
7.0       561
11.0      486
13.0      478
9.0       476
20.0      472
21.0      468
12.0      459
17.0      447
28.0      427
19.0      408
18.0      398
24.0      398
26.0      346
23.0      341
10.0      322
27.0      318
25.0      316
35.0      238
33.0      223
31.0      218
32.0      201
40.0      193
30.0      191
38.0      184
         ...
246.0       3
295.0       3
337.0       3
197.0       3
190.0       3
365.0       3
176.0       2
211.0       2
302.0       2
267.0       2
169.0       2
148.0       2
323.0       2
106.0       2
128.0       2
150.0       2
274.0       2
183.0       1
225.0       1
155.0       1
309.0       1
351.0       1
134.0       1
92.0        1
232.0       1
170.0       1
218.0       1
334.0       1
288.0       1
321.0       1
Name: days_since_last_transaction, dtype: int64

In [19]:
df['days_since_last_transaction'].fillna('0.0', inplace=True)

In [20]:
df.isnull().sum()                #Cross Checking for Missing Values after Imputation

customer_id                       0
vintage                           0
age                               0
gender                            0
dependents                        0
occupation                        0
city                              0
customer_nw_category              0
branch_code                       0
days_since_last_transaction       0
current_balance                   0
previous_month_end_balance        0
average_monthly_balance_prevQ     0
average_monthly_balance_prevQ2    0
current_month_credit              0
previous_month_credit             0
current_month_debit               0
previous_month_debit              0
current_month_balance             0
previous_month_balance            0
churn                             0
dtype: int64

# Dealing with Categorical Variables

In [21]:
df.dtypes     #Identifying Categorical Features and Manipulating Dataset in accordance with them if large unique values

customer_id                         int64
vintage                             int64
age                                 int64
gender                             object
dependents                         object
occupation                         object
city                               object
customer_nw_category                int64
branch_code                         int64
days_since_last_transaction        object
current_balance                   float64
previous_month_end_balance        float64
average_monthly_balance_prevQ     float64
average_monthly_balance_prevQ2    float64
current_month_credit              float64
previous_month_credit             float64
current_month_debit               float64
previous_month_debit              float64
current_month_balance             float64
previous_month_balance            float64
churn                               int64
dtype: object

In [22]:
df.columns

Index(['customer_id', 'vintage', 'age', 'gender', 'dependents', 'occupation',
       'city', 'customer_nw_category', 'branch_code',
       'days_since_last_transaction', 'current_balance',
       'previous_month_end_balance', 'average_monthly_balance_prevQ',
       'average_monthly_balance_prevQ2', 'current_month_credit',
       'previous_month_credit', 'current_month_debit', 'previous_month_debit',
       'current_month_balance', 'previous_month_balance', 'churn'],
      dtype='object')

In [24]:
categorical_cols = ['gender','dependents','occupation','city','days_since_last_transaction']

for i in categorical_cols:                  #Checking Unique Values in Dataset to create dummies avoiding large no of columns
    print('*****', i, '*****')              #One Hot Encoding
    print(df[i].nunique())                  #Avoiding Features with large values later on like dependents, city and days etc
    print('')                               #as they have no effect on model

***** gender *****
2

***** dependents *****
16

***** occupation *****
5

***** city *****
1605

***** days_since_last_transaction *****
361

In [27]:
categorical_cols = ['gender','dependents','occupation','city','days_since_last_transaction']

for i in categorical_cols:                #Printing Unique Values in Dataset
    print('*****', i, '*****')          
    print(df[i].value_counts())             
    print('')

***** gender *****
Male      17073
Female    11309
Name: gender, dtype: int64

***** dependents *****
0.0     21435
0.0      2463
2.0      2150
1.0      1395
3.0       701
4.0       179
5.0        41
6.0         8
7.0         3
52.0        1
50.0        1
36.0        1
32.0        1
25.0        1
9.0         1
8.0         1
Name: dependents, dtype: int64

***** occupation *****
self_employed    17556
salaried          6704
student           2058
retired           2024
company             40
Name: occupation, dtype: int64

***** city *****
1020.0    3479
1096.0    2016
409.0     1334
146.0     1291
834.0     1138
334.0      930
1232.0     840
1020.0     803
623.0      778
15.0       669
575.0      631
1525.0     375
905.0      345
491.0      312
1111.0     312
1494.0     289
649.0      281
1589.0     251
318.0      245
1084.0     240
61.0       237
531.0      227
656.0      197
904.0      187
630.0      166
1271.0     150
1181.0     150
1076.0     133
745.0      130
996.0      119
          ...
728.0        1
727.0        1
772.0        1
777.0        1
839.0        1
782.0        1
838.0        1
1536.0       1
835.0        1
832.0        1
831.0        1
827.0        1
826.0        1
825.0        1
824.0        1
1649.0       1
815.0        1
813.0        1
809.0        1
808.0        1
1539.0       1
798.0        1
793.0        1
790.0        1
789.0        1
788.0        1
785.0        1
784.0        1
783.0        1
985.0        1
Name: city, dtype: int64

***** days_since_last_transaction *****
0.0      3223
0.0      1672
3.0       831
14.0      654
4.0       632
6.0       596
5.0       576
7.0       561
11.0      486
13.0      478
9.0       476
20.0      472
21.0      468
12.0      459
17.0      447
28.0      427
19.0      408
18.0      398
24.0      398
26.0      346
23.0      341
10.0      322
27.0      318
25.0      316
35.0      238
33.0      223
31.0      218
32.0      201
40.0      193
30.0      191
         ...
246.0       3
337.0       3
197.0       3
330.0       3
295.0       3
260.0       3
274.0       2
302.0       2
211.0       2
176.0       2
169.0       2
323.0       2
128.0       2
148.0       2
106.0       2
150.0       2
267.0       2
155.0       1
334.0       1
183.0       1
309.0       1
288.0       1
170.0       1
218.0       1
232.0       1
225.0       1
351.0       1
321.0       1
134.0       1
92.0        1
Name: days_since_last_transaction, dtype: int64

** Generating Dummies Ignoring Categorical Features with large number of Unique Values to avoid great Cardinality in Dummies **

In [26]:
df = pd.get_dummies(df.drop(['dependents','city','days_since_last_transaction'], axis=1))
df.head()            #doing as described above for proceding with model building

,customer_id,vintage,age,customer_nw_category,branch_code,current_balance,previous_month_end_balance,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,...,current_month_balance,previous_month_balance,churn,gender_Female,gender_Male,occupation_company,occupation_retired,occupation_salaried,occupation_self_employed,occupation_student
0,1,3135,66,2,755,1458.71,1458.71,1458.71,1449.07,0.20,...,1458.71,1458.71,0,0,1,0,0,0,1,0
1,2,310,35,2,3214,5390.37,8704.66,7799.26,12419.41,0.56,...,6496.78,8787.61,0,0,1,0,0,0,1,0
2,4,2356,31,2,41,3913.16,5815.29,4910.17,2815.94,0.61,...,5006.28,5070.14,0,0,1,0,0,1,0,0
3,5,478,90,2,582,2291.91,2291.91,2084.54,1006.54,0.47,...,2291.91,1669.79,1,0,0,0,0,0,1,0
4,6,2531,42,3,388,927.72,1401.72,1643.31,1871.12,0.33,...,1157.15,1677.16,1,0,1,0,0,0,1,0

# Logistic Regression

** Using Logistic Regression Algorithm as a Binary Classification Problem for Target Variable churn and faster and most appropriate than knn or others **

### Train Test split

In [27]:
x = df.drop(['churn'],axis=1)
y = df['churn']                     #Seprating Dependent i.e. Target and Independent Variables

In [28]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y= train_test_split(x, y, random_state=101, stratify=y)

### Logistic Regression Model

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score   #importing Logistic Reg Model and using f1score as evaluation metrics

In [30]:
logreg = LogisticRegression()
logreg.fit(train_x, train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

**Making Predictions using predict function **

In [31]:
#Predicting over Train Set and f1_score on the same, f1 is HM of Precision and Recall ranging from 0 to 1
pred_train = logreg.predict(train_x)
k = f1_score(pred_train, train_y)
print("Training F1 Score : ", k)

Training F1 Score :  0.163875056587

In [32]:
#Predicting over Test Set and f1_score on the same, f1 is HM of Precision and Recall ranging from 0 to 1
pred_test = logreg.predict(test_x)
k = f1_score(pred_test, test_y)
print("Testing F1 Score : ", k)

Testing F1 Score :  0.15625

# Random Forest

** Using Random Forest to Evaluate better performance of Model if it could ober LR **

### Train Test Split

In [33]:
x = df.drop(['churn'],axis=1)
y = df['churn']                     #Seprating Dependent i.e. Target and Independent Variables

In [35]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y= train_test_split(x, y, random_state=101, stratify=y)

### Random Forest Model

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score   #importing Logistic Reg Model and using f1score as evaluation metrics

In [37]:
randomforest = RandomForestClassifier()
randomforest.fit(train_x, train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

***Making Predictions using Predict Function ***

In [38]:
#Predicting over Train Set and f1_score on the same, f1 is HM of Precision and Recall ranging from 0 to 1
pred_train = randomforest.predict(train_x)
k = f1_score(pred_train, train_y)
print("Training F1 Score : ", k)

Training F1 Score :  0.958251020677

In [39]:
#Predicting over Test Set and f1_score on the same, f1 is HM of Precision and Recall ranging from 0 to 1
pred_test = randomforest.predict(test_x)
k = f1_score(pred_test, test_y)
print("Testing F1 Score : ", k)

Testing F1 Score :  0.507736943907